from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="accruvia-harness")
    parser.add_argument("--db", default=None, help="Path to the SQLite database.")
    parser.add_argument("--workspace", default=None, help="Path for durable run artifacts.")
    parser.add_argument("--log-path", default=None, help="Path for structured JSONL logs. Defaults under ACCRUVIA_HARNESS_HOME.")
    parser.add_argument("--config-file", default=None, help="Path to the persisted harness config file.")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON instead of human-readable text.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("init-db", help="Initialize the harness database.")
    subparsers.add_parser("config", help="Show resolved harness configuration.")
    subparsers.add_parser("doctor", help="Show operator-facing diagnostics for config, executors, and readiness.")
    reset_state = subparsers.add_parser("reset-local-state", help="Delete repo-local harness state for prototype recovery.")
    reset_state.add_argument("--yes", action="store_true", help="Confirm deletion without an additional prompt.")
    reset_state.add_argument("--keep-config", action="store_true", help="Preserve the persisted config file.")
    subparsers.add_parser("runtime-info", help="Show the configured workflow runtime backend.")
    subparsers.add_parser("run-temporal-worker", help="Start a Temporal worker for the configured task queue.")
    subparsers.add_parser("control-status", help="Show deterministic control-plane state.")
    subparsers.add_parser("control-on", help="Turn on the control-plane master switch and resume active lanes.")
    subparsers.add_parser("control-off", help="Turn off the control-plane master switch and pause active lanes.")
    control_freeze = subparsers.add_parser("control-freeze", help="Freeze the control plane and pause all non-disabled lanes.")
    control_freeze.add_argument("reason")
    subparsers.add_parser("control-thaw", help="Leave the frozen state and return to startup/off semantics.")
    control_pause_lane = subparsers.add_parser("control-pause-lane", help="Pause a control-plane lane.")
    control_pause_lane.add_argument("lane_name")
    control_pause_lane.add_argument("--reason", default="operator_pause")
    control_resume_lane = subparsers.add_parser("control-resume-lane", help="Resume a control-plane lane.")
    control_resume_lane.add_argument("lane_name")
    control_resume_lane.add_argument("--reason", default="operator_resume")
    control_watch_once = subparsers.add_parser("control-watch-once", help="Run one deterministic control watch pass.")
    control_watch_once.add_argument("--api-url")
    control_watch_once.add_argument("--stalled-objective-hours", type=float, default=6.0)
    control_watch_once.add_argument("--no-freeze-on-stall", action="store_true")
    control_loop = subparsers.add_parser("control-loop", help="Run the deterministic control-plane watch loop continuously.")
    control_loop.add_argument("--api-url")
    control_loop.add_argument("--interval-seconds", type=float, default=60.0)
    control_loop.add_argument("--stalled-objective-hours", type=float, default=6.0)
    control_loop.add_argument("--no-freeze-on-stall", action="store_true")
    control_loop.add_argument("--max-iterations", type=int)
    subparsers.add_parser("control-sa-watch-once", help="Run one sa-watch intervention pass.")
    sa_watch_start = subparsers.add_parser("sa-watch-start", help="Start sa-watch as a detached background process.")
    sa_watch_start.add_argument("--interval-seconds", type=float, default=1200.0)
    subparsers.add_parser("sa-watch-stop", help="Stop the running sa-watch background process and clear desired state.")
    subparsers.add_parser("sa-watch-status", help="Show sa-watch desired and runtime state.")
    sa_watch_loop = subparsers.add_parser("sa-watch-loop", help="Run the sa-watch continuity loop continuously.")
    sa_watch_loop.add_argument("--interval-seconds", type=float, default=1200.0)
    sa_watch_loop.add_argument("--max-iterations", type=int)
    setup = subparsers.add_parser("setup", help="Run the interactive first-run operator onboarding flow.")
    setup.add_argument("--yes", action="store_true", help="Accept detected defaults without prompting where possible.")
    setup.add_argument("--skip-other-detected", action="store_true", help="Persist only the selected LLM executor.")
    setup.add_argument("--custom-command", default=None, help="Use a custom generic command instead of an autodetected CLI.")
    configure_llm = subparsers.add_parser("configure-llm", help="Persist durable LLM executor settings.")
    configure_llm.add_argument("--backend", choices=["auto", "command", "codex", "claude", "accruvia_client"])
    configure_llm.add_argument("--command", dest="llm_command_value")
    configure_llm.add_argument("--codex-command", dest="llm_codex_command_value")
    configure_llm.add_argument("--claude-command", dest="llm_claude_command_value")
    configure_llm.add_argument("--accruvia-client-command", dest="llm_accruvia_client_command_value")
    configure_llm.add_argument("--env-passthrough", action="append", default=None)
    configure_llm.add_argument("--clear-existing", action="store_true")

    create_project = subparsers.add_parser("create-project", help="Create a project.")
    create_project.add_argument("name")
    create_project.add_argument("description")
    create_project.add_argument("--adapter-name", default="generic")
    create_project.add_argument("--workspace-policy", choices=["isolated_required", "isolated_preferred", "shared_allowed"])
    create_project.add_argument("--promotion-mode", choices=["direct_main", "branch_only", "branch_and_pr"])
    create_project.add_argument("--repo-provider", choices=["github", "gitlab"])
    create_project.add_argument("--repo-name")
    create_project.add_argument("--base-branch")
    create_project.add_argument("--no-bootstrap-heartbeat", action="store_true")

    update_project = subparsers.add_parser("update-project", help="Update project policy and repository settings.")
    update_project.add_argument("project_id")
    update_project.add_argument("--name")
    update_project.add_argument("--description")
    update_project.add_argument("--adapter-name")
    update_project.add_argument("--workspace-policy", choices=["isolated_required", "isolated_preferred", "shared_allowed"])
    update_project.add_argument("--promotion-mode", choices=["direct_main", "branch_only", "branch_and_pr"])
    update_project.add_argument("--repo-provider", choices=["github", "gitlab"])
    update_project.add_argument("--repo-name")
    update_project.add_argument("--base-branch")
    update_project.add_argument("--max-concurrent-tasks", type=int)

    create_task = subparsers.add_parser("create-task", help="Create a task.")
    create_task.add_argument("project_id")
    create_task.add_argument("title")
    create_task.add_argument("objective")
    create_task.add_argument("--objective-id")
    create_task.add_argument("--priority", type=int, default=100)
    create_task.add_argument("--external-ref-type")
    create_task.add_argument("--external-ref-id")
    create_task.add_argument("--validation-profile", default="generic")
    create_task.add_argument("--validation-mode", default="default_focused")
    create_task.add_argument("--strategy", default="default")
    create_task.add_argument("--max-attempts", type=int, default=3)
    create_task.add_argument("--max-branches", type=int, default=1)
    create_task.add_argument("--required-artifact", action="append", dest="required_artifacts", default=None)
    create_task.add_argument("--allowed-path", action="append", dest="allowed_paths", default=None)
    create_task.add_argument("--forbidden-path", action="append", dest="forbidden_paths", default=None)

    run_once = subparsers.add_parser("run-once", help="Run one full harness cycle for a task.")
    run_once.add_argument("task_id")

    auto_merge = subparsers.add_parser("auto-merge-run", help="Run the merge gate for a completed run.")
    auto_merge.add_argument("run_id")
    auto_merge.add_argument("--dry-run", action="store_true", help="Evaluate without executing the merge.")
    auto_merge.add_argument("--target-branch", default="main", help="Target branch for the merge.")

    request = subparsers.add_parser("request", help="Describe a feature in plain language. The harness translates it into a technical task and executes it.")
    request.add_argument("intent", help="What you want, in your own words.")
    request.add_argument("--project-id", help="Project to create the task in.")
    request.add_argument("--dry-run", action="store_true", help="Show the translated task without executing it.")

    run_until_stable = subparsers.add_parser("run-until-stable", help="Run repeated cycles until a task is completed or failed.")
    run_until_stable.add_argument("task_id")

    process_next = subparsers.add_parser("process-next", help="Select the highest-priority pending task and process it until stable.")
    process_next.add_argument("--project-id")
    process_next.add_argument("--worker-id", default="local-worker")
    process_next.add_argument("--lease-seconds", type=int, default=300)

    process_queue = subparsers.add_parser("process-queue", help="Process up to N pending tasks in priority order.")
    process_queue.add_argument("limit", type=int)
    process_queue.add_argument("--project-id")
    process_queue.add_argument("--worker-id", default="local-worker")
    process_queue.add_argument("--lease-seconds", type=int, default=300)

    supervise = subparsers.add_parser(
        "run-harness",
        help="Advance the queue continuously, watching for new work and scheduled heartbeats until stopped.",
    )
    supervise.add_argument("--project-id")
    supervise.add_argument("--worker-id", default="harness")
    supervise.add_argument("--lease-seconds", type=int, default=300)
    supervise.set_defaults(watch=True)
    supervise.add_argument("--one-shot", dest="watch", action="store_false", help="Drain current work and exit when idle.")
    supervise.add_argument("--idle-sleep-seconds", type=float, default=30.0)
    supervise.add_argument("--max-idle-cycles", type=int)
    supervise.add_argument("--max-iterations", type=int)
    supervise.add_argument("--heartbeat-project-id", action="append", dest="heartbeat_project_ids", default=None)
    supervise.add_argument("--heartbeat-interval-seconds", type=float)
    supervise.add_argument("--heartbeat-all-projects", action="store_true")
    supervise.add_argument("--review-check-enabled", action="store_true")
    supervise.add_argument("--review-check-interval-seconds", type=int)
    subparsers.add_parser("stop-supervisors", help="Request a graceful stop for running harness processes.")
    subparsers.add_parser("kill-supervisors", help="Force-kill running harness processes immediately.")

    runtime_run = subparsers.add_parser("run-runtime", help="Run a task through the configured workflow runtime backend.")
    runtime_run.add_argument("task_id")

    runtime_process_next = subparsers.add_parser("process-next-runtime", help="Process the next pending task through the configured workflow runtime backend.")
    runtime_process_next.add_argument("--project-id")
    runtime_process_next.add_argument("--worker-id", default="local-worker")
    runtime_process_next.add_argument("--lease-seconds", type=int, default=300)

    import_issue = subparsers.add_parser("import-issue", help="Create a harness task from an external issue reference.")
    import_issue.add_argument("project_id")
    import_issue.add_argument("issue_id")
    import_issue.add_argument("title")
    import_issue.add_argument("objective")
    import_issue.add_argument("--priority", type=int, default=100)
    import_issue.add_argument("--validation-profile", default="generic")
    import_issue.add_argument("--strategy", default="default")
    import_issue.add_argument("--max-attempts", type=int, default=3)
    import_issue.add_argument("--required-artifact", action="append", dest="required_artifacts", default=None)

    for name, help_text in [
        ("import-github-issue", "Fetch a GitHub issue and create or reuse a linked harness task."),
        ("import-gitlab-issue", "Fetch a GitLab issue and create or reuse a linked harness task."),
    ]:
        cmd = subparsers.add_parser(name, help=help_text)
        cmd.add_argument("project_id")
        cmd.add_argument("repo")
        cmd.add_argument("issue_id")
        cmd.add_argument("--priority", type=int, default=100)
        cmd.add_argument("--validation-profile", default="generic")
        cmd.add_argument("--strategy", default="default")
        cmd.add_argument("--max-attempts", type=int, default=3)
        cmd.add_argument("--required-artifact", action="append", dest="required_artifacts", default=None)

    for name, help_text in [
        ("sync-github-open", "Import or reuse open GitHub issues as linked harness tasks."),
        ("sync-gitlab-open", "Import or reuse open GitLab issues as linked harness tasks."),
    ]:
        cmd = subparsers.add_parser(name, help=help_text)
        cmd.add_argument("project_id")
        cmd.add_argument("repo")
        cmd.add_argument("--limit", type=int, default=20)
        cmd.add_argument("--priority", type=int, default=100)
        cmd.add_argument("--validation-profile", default="generic")
        cmd.add_argument("--strategy", default="default")
        cmd.add_argument("--max-attempts", type=int, default=3)
        cmd.add_argument("--required-artifact", action="append", dest="required_artifacts", default=None)

    for name, help_text in [
        ("report-github", "Post a comment back to a GitHub-linked task and optionally close the issue."),
        ("report-gitlab", "Post a comment back to a GitLab-linked task and optionally close the issue."),
    ]:
        cmd = subparsers.add_parser(name, help=help_text)
        cmd.add_argument("task_id")
        cmd.add_argument("repo")
        cmd.add_argument("--comment")
        cmd.add_argument("--close", action="store_const", const=True, default=None)

    sync_github_state = subparsers.add_parser("sync-github-state", help="Synchronize a GitHub-linked issue state from the current harness task status.")
    sync_github_state.add_argument("task_id")
    sync_github_state.add_argument("repo")
    sync_gitlab_state = subparsers.add_parser("sync-gitlab-state", help="Synchronize a GitLab-linked issue state from the current harness task status.")
    sync_gitlab_state.add_argument("task_id")
    sync_gitlab_state.add_argument("repo")
    sync_github_metadata = subparsers.add_parser("sync-github-metadata", help="Synchronize labels, milestone, and assignees from a GitHub issue into task metadata.")
    sync_github_metadata.add_argument("task_id")
    sync_github_metadata.add_argument("repo")
    sync_gitlab_metadata = subparsers.add_parser("sync-gitlab-metadata", help="Synchronize labels, milestone, and assignees from a GitLab issue into task metadata.")
    sync_gitlab_metadata.add_argument("task_id")
    sync_gitlab_metadata.add_argument("repo")

    review = subparsers.add_parser("review-promotion", help="Run promotion validation for a completed task run.")
    review.add_argument("task_id")
    review.add_argument("--run-id")
    review.add_argument("--no-follow-on", action="store_true")

    affirm = subparsers.add_parser("affirm-promotion", help="Ask the configured LLM executor to affirm or reject a pending promotion.")
    affirm.add_argument("task_id")
    affirm.add_argument("--run-id")
    affirm.add_argument("--promotion-id")
    affirm.add_argument("--no-follow-on", action="store_true")

    rereview = subparsers.add_parser("rereview-promotion", help="Re-review a previously failed promotion using a remediation task run.")
    rereview.add_argument("task_id")
    rereview.add_argument("remediation_task_id")
    rereview.add_argument("--remediation-run-id")
    rereview.add_argument("--base-promotion-id")
    rereview.add_argument("--no-follow-on", action="store_true")

    smoke = subparsers.add_parser("smoke-test", help="Run a local end-to-end smoke test from project creation through task completion.")
    smoke.add_argument("--project-name", default="smoke-project")
    smoke.add_argument("--task-title", default="Smoke task")
    smoke.add_argument("--objective", default="Verify the local durable loop")
    subparsers.add_parser("ci-local", help="Run the local GitHub CI parity gate.")

    subparsers.add_parser("status", help="Show projects, tasks, runs, and promotions.")
    summary = subparsers.add_parser("summary", help="Show high-level harness summary.")
    summary.add_argument("--project-id")
    context_packet = subparsers.add_parser("context-packet", help="Export a compact read-only summary for LLM interrogation.")
    context_packet.add_argument("--project-id")
    ops_report = subparsers.add_parser("ops-report", help="Show operational backlog and profile-aware promotion metrics.")
    ops_report.add_argument("--project-id")
    subparsers.add_parser("telemetry-report", help="Show aggregated telemetry counters and span timings.")
    dashboard_report = subparsers.add_parser("dashboard-report", help="Show a small operational dashboard export.")
    dashboard_report.add_argument("--project-id")
    ui = subparsers.add_parser("ui", help="Start the local harness API backend for the separate frontend.")
    ui.add_argument("--project-id")
    ui.add_argument("--host", default="127.0.0.1")
    ui.add_argument("--port", type=int, default=9100)
    ui.add_argument("--no-open-browser", action="store_true")
    heartbeat = subparsers.add_parser("heartbeat", help="Run a project heartbeat using the configured cognition adapter.")
    heartbeat.add_argument("project_id")
    heartbeat.add_argument("--worker-id", default="heartbeat-worker")
    heartbeat.add_argument("--lease-seconds", type=int, default=300)
    heartbeat.add_argument("--no-process-created-tasks", action="store_true")
    explain_system = subparsers.add_parser("explain-system", help="Use the configured LLM executor to explain the current system state from read-only evidence.")
    explain_system.add_argument("--project-id")
    lineage_report = subparsers.add_parser("lineage-report", help="Show ancestors and spawned child tasks for a task.")
    lineage_report.add_argument("task_id")
    task_report = subparsers.add_parser("task-report", help="Show task lineage and evidence.")
    task_report.add_argument("task_id")
    explain_task = subparsers.add_parser("explain-task", help="Use the configured LLM executor to explain a task from read-only evidence.")
    explain_task.add_argument("task_id")
    red_team_mermaid = subparsers.add_parser("red-team-mermaid", help="Red-team a Mermaid diagram from a spec or .mmd file before human review.")
    red_team_mermaid.add_argument("path", help="Path to a markdown spec or Mermaid file.")
    red_team_mermaid.add_argument("--block-index", type=int, default=0, help="Zero-based Mermaid block index to review inside a markdown file.")
    red_team_mermaid.add_argument("--no-llm", action="store_true", help="Skip the optional LLM critique pass.")
    red_team_mermaid.add_argument("--model", default=None, help="Optional model override for the LLM critique pass.")
    events = subparsers.add_parser("events", help="Show recorded harness events.")
    events.add_argument("--entity-type")
    events.add_argument("--entity-id")
    check_reviews = subparsers.add_parser("check-reviews", help="Check open PR/MR promotions for merge or conflict state.")
    check_reviews.add_argument("--interval-seconds", type=int)
    nudge_project = subparsers.add_parser("nudge-project", help="Record an operator nudge, run a heartbeat, and gracefully reload project supervision when needed.")
    nudge_project.add_argument("project_id")
    nudge_project.add_argument("note")
    nudge_project.add_argument("--worker-id", default="nudge-worker")
    nudge_project.add_argument("--lease-seconds", type=int, default=300)
    nudge_project.add_argument("--restart-timeout-seconds", type=int, default=300)
    nudge_project.add_argument("--no-heartbeat", action="store_true")
    nudge_project.add_argument("--no-process-created-tasks", action="store_true")
    nudge_project.add_argument("--no-restart-running-supervisors", action="store_true")

    chaos = subparsers.add_parser("chaos", help="Run focused chaos checks for recovery and control-plane invariants.")
    chaos.add_argument("--project-id", help="Feed findings back to this project as proposed tasks.")
    chaos.add_argument("--memory-limit-mb", type=int, default=2048, help="Memory limit for sandbox.")
    chaos.add_argument("--cpu-limit-seconds", type=int, default=300, help="CPU time limit for sandbox.")
    chaos.add_argument("--report-path", help="Write JSON report to this path.")
    chaos.add_argument("--min-severity", choices=["critical", "high", "medium", "low"], default="high", help="Minimum severity to feed back as tasks.")
    chaos.add_argument("--dry-run", action="store_true", help="Run chaos but do not create tasks in production.")
    chaos.add_argument("--all-injectors", action="store_true", help="Include broader synthetic injectors instead of the focused default set.")
    chaos.add_argument("--shadow-iterations", type=int, default=10, help="Max supervisor iterations for shadow supervisor injector.")
    chaos.add_argument("--shadow-heartbeat-interval", type=float, default=None, help="Heartbeat interval for shadow supervisor (enables heartbeat in shadow).")

    return parser
