import { createApp } from 'vue'
import { createVuetify } from 'vuetify'
import {
  VApp,
  VBtn,
  VCard,
  VChip,
  VChipGroup,
  VCol,
  VContainer,
  VIcon,
  VList,
  VListItem,
  VListItemSubtitle,
  VListItemTitle,
  VMain,
  VNavigationDrawer,
  VRow,
  VSpacer,
  VTextField,
} from 'vuetify/components'
import { Ripple } from 'vuetify/directives'
import { aliases as mdiAliases, mdi } from 'vuetify/iconsets/mdi-svg'
import 'vuetify/styles'
import {
  mdiAccessPoint,
  mdiAlertCircle,
  mdiArrowLeft,
  mdiBookOpenVariant,
  mdiCheck,
  mdiCheckCircle,
  mdiCircle,
  mdiCircleOutline,
  mdiClockOutline,
  mdiCloseCircle,
  mdiCogOutline,
  mdiChartBox,
  mdiFormatListBulleted,
  mdiHelpCircle,
  mdiLoading,
  mdiPlay,
  mdiRocketLaunch,
  mdiSend,
  mdiSourceBranch,
  mdiViewDashboard,
} from '@mdi/js'
import App from './App.vue'
import router from './plugins/router'

const accruvia = {
  dark: false,
  colors: {
    background: '#f3ecdf',
    surface: '#fffaf2',
    'surface-bright': '#ffffff',
    'surface-light': '#f6efe3',
    'surface-variant': '#e1d4bf',
    primary: '#b35c2e',
    'primary-darken-1': '#8f451d',
    secondary: '#5f7650',
    'secondary-darken-1': '#43573a',
    error: '#c45a4f',
    info: '#3979b5',
    success: '#4d7b5a',
    warning: '#c28b2c',
    'on-background': '#2f241b',
    'on-surface': '#2f241b',
    'on-surface-variant': '#6e6256',
    'on-primary': '#fff8f0',
  },
}

const vuetify = createVuetify({
  components: {
    VApp,
    VBtn,
    VCard,
    VChip,
    VChipGroup,
    VCol,
    VContainer,
    VIcon,
    VList,
    VListItem,
    VListItemSubtitle,
    VListItemTitle,
    VMain,
    VNavigationDrawer,
    VRow,
    VSpacer,
    VTextField,
  },
  directives: { Ripple },
  icons: {
    defaultSet: 'mdi',
    aliases: {
      ...mdiAliases,
      accessPoint: mdiAccessPoint,
      alertCircle: mdiAlertCircle,
      arrowLeft: mdiArrowLeft,
      bookOpenVariant: mdiBookOpenVariant,
      check: mdiCheck,
      checkCircle: mdiCheckCircle,
      circle: mdiCircle,
      circleOutline: mdiCircleOutline,
      cogOutline: mdiCogOutline,
      chartBox: mdiChartBox,
      clockOutline: mdiClockOutline,
      closeCircle: mdiCloseCircle,
      formatListBulleted: mdiFormatListBulleted,
      helpCircle: mdiHelpCircle,
      loading: mdiLoading,
      play: mdiPlay,
      rocketLaunch: mdiRocketLaunch,
      send: mdiSend,
      sourceBranch: mdiSourceBranch,
      viewDashboard: mdiViewDashboard,
    },
    sets: { mdi },
  },
  theme: {
    defaultTheme: 'accruvia',
    themes: { accruvia },
  },
  defaults: {
    VCard: { rounded: 'sm', elevation: 0 },
    VBtn: { rounded: 'sm', variant: 'flat' },
    VChip: { rounded: 'sm', size: 'small' },
    VTextField: { variant: 'outlined', density: 'compact' },
  },
})

createApp(App).use(vuetify).use(router).mount('#app')
